### ISSUE TITLE
viewStore descendants

### ISSUE THREAD

**Issue by dalimetric** [emilwidlund/framer-joystick#4]
Hi Emil

I am following along with the setup article here
https://blog.framer.com/introducing-framer-joystick-28359287bef0

and hit a snag pretty quickly:
![image](https://user-images.githubusercontent.com/40117754/43721089-e08b2298-995f-11e8-8090-118e60337d66.png)

The module loads correctly, and my code is as follows. Not sure if there has been any breaking updated on the Framer side?
![image](https://user-images.githubusercontent.com/40117754/43721224-3c53cbe8-9960-11e8-96c7-006ed6d75da0.png)

Thank you for any assistance!

**Comment by blaineb** [comment]
I'm having the same problem :(

**Comment by emilwidlund** [comment]
Sorry for this late reply. 

I've just reverted the last merged pull request. Clone the repository again and it should work as intended.

**Comment by dalimetric** [comment]
Thank you @emilwidlund !
